function handleError(error) {
    console.log(error, error.stack);
};

module.exports = handleError;